// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1A69x9tZfQ4cV7C66AT-nI9pbYPp7JQ',
    appId: '1:29224761808:web:103b63b454d35a4380e1d5',
    messagingSenderId: '29224761808',
    projectId: 'edugen-ad771',
    authDomain: 'edugen-ad771.firebaseapp.com',
    storageBucket: 'edugen-ad771.appspot.com',
    measurementId: 'G-HTPMN67BZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ncnbSB-1beuVxrWKvnG5AnG3gvVZo70',
    appId: '1:29224761808:android:cc1fffd49b96b5ff80e1d5',
    messagingSenderId: '29224761808',
    projectId: 'edugen-ad771',
    storageBucket: 'edugen-ad771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcyKwvcA7PQpCwXYEPp8z7-FNo5jj4z7Y',
    appId: '1:29224761808:ios:3ca693b89d7de47780e1d5',
    messagingSenderId: '29224761808',
    projectId: 'edugen-ad771',
    storageBucket: 'edugen-ad771.appspot.com',
    iosBundleId: 'com.example.astrolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcyKwvcA7PQpCwXYEPp8z7-FNo5jj4z7Y',
    appId: '1:29224761808:ios:3ca693b89d7de47780e1d5',
    messagingSenderId: '29224761808',
    projectId: 'edugen-ad771',
    storageBucket: 'edugen-ad771.appspot.com',
    iosBundleId: 'com.example.astrolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq1A69x9tZfQ4cV7C66AT-nI9pbYPp7JQ',
    appId: '1:29224761808:web:84f469bc816628d080e1d5',
    messagingSenderId: '29224761808',
    projectId: 'edugen-ad771',
    authDomain: 'edugen-ad771.firebaseapp.com',
    storageBucket: 'edugen-ad771.appspot.com',
    measurementId: 'G-QGTTX1D1KK',
  );

}